version: '3'

services:
  web:
    build: .
    restart: always
    command: bash -c "cd /app/code && gunicorn -w 2 -b :8000 app:app"
    volumes:
      - ./code:/app/code
    ports:
      - "8000:8000"
    environment:
      - DEBUG_MODE=True

